In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [92]:
import pandas as pd
import nltk
import re
import numpy as np
from nltk.corpus import stopwords
import tensorflow as tf
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.preprocessing.text import one_hot

In [93]:
df = pd.read_csv("/content/drive/MyDrive/NLP/AI ML Python/Tweet_NFT.xlsx - Sheet1.csv")
df.head()

id                                         tweet_text  \
0  1212762  @crypto_brody @eCoLoGy1990 @MoonrunnersNFT @It...   
1  1212763  Need Sick Character art❓#art #artist #Artist...   
2  1212765  @The_Hulk_NFT @INagotchiNFT @Tesla @killabears...   
3  1212766  @CryptoBatzNFT @DarekBTW The first project in ...   
4  1212767  @sashadysonn The first project in crypto with ...   

           tweet_created_at  tweet_intent  
0  2022-08-06T16:56:36.000Z     Community  
1  2022-08-06T16:56:36.000Z      Giveaway  
2  2022-08-06T16:56:35.000Z  Appreciation  
3  2022-08-06T16:56:35.000Z     Community  
4  2022-08-06T16:56:34.000Z     Community

In [94]:
df['tweet_intent'].value_counts()

Community         41510
Giveaway          21041
Appreciation      16451
Whitelist          8320
Presale            5107
Done               3049
pinksale            477
Interested          276
Launching Soon      133
Name: tweet_intent, dtype: int64

In [95]:
df.isnull().sum()

id                      0
tweet_text              0
tweet_created_at        0
tweet_intent        31089
dtype: int64

In [96]:
st = 127453-31089
train_df = df.iloc[:st,:]
test_df = df.iloc[st:,:]
train_df.shape,test_df.shape

((96364, 4), (31089, 4))

In [97]:
train_df.isnull().sum()

id                  0
tweet_text          0
tweet_created_at    0
tweet_intent        0
dtype: int64

In [98]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [99]:
### Data preprocessing
voca_size = 50000
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
corpus = []
for i in range(0,len(train_df)):
    print(i)
    review = re.sub('[^a-zA-Z]', ' ' , train_df['tweet_text'][i])
    review = review.lower()
    review = review.split()
    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

Streaming output truncated to the last 5000 lines.
91364
91365
91366
91367
91368
91369
91370
91371
91372
91373
91374
91375
91376
91377
91378
91379
91380
91381
91382
91383
91384
91385
91386
91387
91388
91389
91390
91391
91392
91393
91394
91395
91396
91397
91398
91399
91400
91401
91402
91403
91404
91405
91406
91407
91408
91409
91410
91411
91412
91413
91414
91415
91416
91417
91418
91419
91420
91421
91422
91423
91424
91425
91426
91427
91428
91429
91430
91431
91432
91433
91434
91435
91436
91437
91438
91439
91440
91441
91442
91443
91444
91445
91446
91447
91448
91449
91450
91451
91452
91453
91454
91455
91456
91457
91458
91459
91460
91461
91462
91463
91464
91465
91466
91467
91468
91469
91470
91471
91472
91473
91474
91475
91476
91477
91478
91479
91480
91481
91482
91483
91484
91485
91486
91487
91488
91489
91490
91491
91492
91493
91494
91495
91496
91497
91498
91499
91500
91501
91502
91503
91504
91505
91506
91507
91508
91509
91510
91511
91512
91513
91514
91515
91516
91517
91518
91519
91520
91521
9

In [100]:
corpus

['crypto brodi ecolog moonrunnersnft itsukinft thelittlesnft spacerid nft wdoopsi womenandweapon wowpixiesnft bokinft quirkiesnft bitcoin bowi kal el krypto sophiegreen new cryptocurr born fan chihuahua meme commun simpli pet love keep transact automat distribut ca x fd c b dea e b f chihuahua bsc tg http co wqszcivfam',
 'need sick charact art art artist artist anim illustr illustr illustrationart nft nftgiveaway danim dart conceptart concept illustr solananft artistontwitt scrimfind blazedrt sgh rt smallstreamhyp shoutgam http co nf egckt',
 'hulk nft inagotchinft tesla killabearsnft elonmusk great choic tesla good luck',
 'cryptobatznft darekbtw first project crypto move earn astrobirdz big thing happen project releas marketplac nest feedtoearn birdzarmi luna btc web gem nft nftcommun http co cu xoromr http co quvoj ysyp',
 'sashadysonn first project crypto move earn astrobirdz big thing happen project releas marketplac nest feedtoearn birdzarmi luna btc web gem nft nftcommun http c

In [101]:
onehot_rep = [one_hot(words,voca_size) for words in corpus]

In [102]:
onehot_rep

[[43635,
  32317,
  48946,
  16576,
  6572,
  9872,
  2762,
  30072,
  44949,
  22481,
  28402,
  36675,
  43045,
  24346,
  986,
  579,
  37287,
  31479,
  13117,
  24366,
  42188,
  32909,
  1927,
  37518,
  39597,
  33903,
  43778,
  49124,
  34289,
  29120,
  40006,
  19977,
  7306,
  2387,
  34712,
  6162,
  49603,
  2101,
  31758,
  29672,
  2101,
  25344,
  37518,
  22292,
  19510,
  25589,
  38036,
  36964],
 [22504,
  40396,
  8598,
  22008,
  22008,
  44401,
  44401,
  600,
  34478,
  34478,
  49233,
  30072,
  40381,
  11121,
  31548,
  23368,
  48629,
  34478,
  17514,
  16568,
  36250,
  5215,
  11618,
  34741,
  45884,
  42620,
  25589,
  38036,
  17498,
  39607],
 [39728, 30072, 33176, 26165, 42628, 37374, 46509, 12679, 26165, 2361, 5022],
 [9628,
  20000,
  5535,
  18802,
  43635,
  39797,
  13497,
  47019,
  40264,
  24125,
  35691,
  18802,
  45339,
  4534,
  38414,
  46119,
  36747,
  33784,
  19944,
  6708,
  24177,
  30072,
  9873,
  25589,
  38036,
  33131,
  8646

In [103]:
sen_length = 50
embadding_doc = pad_sequences(onehot_rep,padding='pre', maxlen=sen_length)
print(embadding_doc)

[[    0     0 43635 ... 25589 38036 36964]
 [    0     0     0 ... 38036 17498 39607]
 [    0     0     0 ... 26165  2361  5022]
 ...
 [    0     0     0 ...  4120  5705 33050]
 [    0     0     0 ... 25589 38036 11924]
 [    0     0     0 ... 40839 20528 24956]]


In [104]:
train_df['tweet_intent'].unique()


array(['Community', 'Giveaway', 'Appreciation', 'Presale', 'Whitelist',
       'pinksale', 'Done', 'Interested', 'Launching Soon'], dtype=object)

In [105]:
result = {'Community':2, 'Giveaway':4, 'Appreciation':1, 'Presale':7, 'Whitelist':9,
       'pinksale':8, 'Done':3, 'Interested':5, 'Launching Soon':6}

In [106]:
train_df['tweet_intent'] = train_df['tweet_intent'].map(result)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [107]:
train_df['tweet_intent']

0        2
1        4
2        1
3        2
4        2
        ..
96359    1
96360    7
96361    1
96362    2
96363    1
Name: tweet_intent, Length: 96364, dtype: int64

In [108]:
X_final = np.array(embadding_doc)
Y_final = np.array(train_df['tweet_intent'])

In [109]:
from sklearn.model_selection import train_test_split
X_train,x_test,Y_train,y_test = train_test_split(X_final,Y_final,test_size=0.25,random_state=42)

In [113]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import precision_recall_fscore_support as score
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

In [114]:
rf = RandomForestClassifier(n_estimators=500, max_depth=12, n_jobs=-1)
rf_model = rf.fit(X_train, Y_train)

In [115]:
y_pred_prob = rf_model.predict_proba(x_test)
print(y_pred_prob)

[[5.85868724e-06 9.96650183e-01 1.51825963e-06 ... 3.11356737e-07
  0.00000000e+00 2.38098644e-03]
 [1.83740797e-02 2.23683333e-02 1.13548795e-03 ... 1.24293117e-03
  1.09994924e-04 5.83277681e-03]
 [5.85868724e-06 9.96735766e-01 1.51825963e-06 ... 3.11356737e-07
  0.00000000e+00 2.28761542e-03]
 ...
 [6.68543091e-03 9.70474625e-01 3.70493674e-04 ... 5.93677175e-04
  6.18674102e-06 7.02993267e-03]
 [5.37015539e-01 1.57869998e-01 8.52571849e-02 ... 4.89791409e-02
  0.00000000e+00 5.16401318e-02]
 [5.40589906e-03 2.01139859e-02 4.43901573e-04 ... 1.43878999e-03
  2.34686647e-03 9.53690066e-01]]


In [117]:
y_pred = rf_model.predict(x_test)

In [118]:
print(confusion_matrix(y_test,y_pred)) 
print('---------------------------------------------------')
print(classification_report(y_test,y_pred))  
print('---------------------------------------------------')
print(accuracy_score(y_test, y_pred)) 

[[2816  523    5  790    0    0   14    0    3]
 [ 573 8852    4  878    0    0   10    0    3]
 [ 236   66  402   69    0    0    0    0    0]
 [ 540  648   13 4032    0    0   33    0    7]
 [  30   16    0   20    0    0    0    0    0]
 [   1   13    0    5    0   17    0    0    0]
 [  60   46    0   45    0    0 1091    0    1]
 [   0   17    0   16    0    0    0   78    2]
 [ 232  363    0  333    0    0   72    1 1115]]
---------------------------------------------------
              precision    recall  f1-score   support

           1       0.63      0.68      0.65      4151
           2       0.84      0.86      0.85     10320
           3       0.95      0.52      0.67       773
           4       0.65      0.76      0.70      5273
           5       0.00      0.00      0.00        66
           6       1.00      0.47      0.64        36
           7       0.89      0.88      0.89      1243
           8       0.99      0.69      0.81       113
           9       0.99     

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [121]:
from xgboost import XGBClassifier
mdl_xgb = XGBClassifier(n_estimators = 100, learning_rate = 0.1, max_depth =10)
mdl_xgb.fit(X_train, Y_train)
y_pred = mdl_xgb.predict(x_test)

print(confusion_matrix(y_test,y_pred)) 
print('---------------------------------------------------')
print(classification_report(y_test,y_pred))  
print('---------------------------------------------------')
print(accuracy_score(y_test, y_pred)) 

[[3467  437    7  220    1    0    2    0   17]
 [ 282 9787    4  226    0    0    5    0   16]
 [  89   59  594   29    0    0    0    0    2]
 [ 271  366    6 4590    0    0   14    0   26]
 [  19   28    0    6   13    0    0    0    0]
 [   1    3    0    2    0   30    0    0    0]
 [  27   18    0   16    0    0 1177    0    5]
 [   0    5    0    5    0    0    0  103    0]
 [ 201  320    0  138    0    0   25    2 1430]]
---------------------------------------------------
              precision    recall  f1-score   support

           1       0.80      0.84      0.81      4151
           2       0.89      0.95      0.92     10320
           3       0.97      0.77      0.86       773
           4       0.88      0.87      0.87      5273
           5       0.93      0.20      0.32        66
           6       1.00      0.83      0.91        36
           7       0.96      0.95      0.95      1243
           8       0.98      0.91      0.94       113
           9       0.96     

In [122]:
### Data preprocessing
voca_size = 50000
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
corpus_test = []
for i in range(0,len(train_df)):
    print(i)
    review_1 = re.sub('[^a-zA-Z]', ' ' , train_df['tweet_text'][i])
    review_1 = review_1.lower()
    review_1 = review_1.split()
    review_1 = [ps.stem(word) for word in review_1 if not word in stopwords.words('english')]
    review_1 = ' '.join(review_1)
    corpus_test.append(review_1)

Streaming output truncated to the last 5000 lines.
91364
91365
91366
91367
91368
91369
91370
91371
91372
91373
91374
91375
91376
91377
91378
91379
91380
91381
91382
91383
91384
91385
91386
91387
91388
91389
91390
91391
91392
91393
91394
91395
91396
91397
91398
91399
91400
91401
91402
91403
91404
91405
91406
91407
91408
91409
91410
91411
91412
91413
91414
91415
91416
91417
91418
91419
91420
91421
91422
91423
91424
91425
91426
91427
91428
91429
91430
91431
91432
91433
91434
91435
91436
91437
91438
91439
91440
91441
91442
91443
91444
91445
91446
91447
91448
91449
91450
91451
91452
91453
91454
91455
91456
91457
91458
91459
91460
91461
91462
91463
91464
91465
91466
91467
91468
91469
91470
91471
91472
91473
91474
91475
91476
91477
91478
91479
91480
91481
91482
91483
91484
91485
91486
91487
91488
91489
91490
91491
91492
91493
91494
91495
91496
91497
91498
91499
91500
91501
91502
91503
91504
91505
91506
91507
91508
91509
91510
91511
91512
91513
91514
91515
91516
91517
91518
91519
91520
91521
9

In [123]:
onehot_rep_test = [one_hot(words,voca_size) for words in corpus_test]
onehot_rep_test 

[[43635,
  32317,
  48946,
  16576,
  6572,
  9872,
  2762,
  30072,
  44949,
  22481,
  28402,
  36675,
  43045,
  24346,
  986,
  579,
  37287,
  31479,
  13117,
  24366,
  42188,
  32909,
  1927,
  37518,
  39597,
  33903,
  43778,
  49124,
  34289,
  29120,
  40006,
  19977,
  7306,
  2387,
  34712,
  6162,
  49603,
  2101,
  31758,
  29672,
  2101,
  25344,
  37518,
  22292,
  19510,
  25589,
  38036,
  36964],
 [22504,
  40396,
  8598,
  22008,
  22008,
  44401,
  44401,
  600,
  34478,
  34478,
  49233,
  30072,
  40381,
  11121,
  31548,
  23368,
  48629,
  34478,
  17514,
  16568,
  36250,
  5215,
  11618,
  34741,
  45884,
  42620,
  25589,
  38036,
  17498,
  39607],
 [39728, 30072, 33176, 26165, 42628, 37374, 46509, 12679, 26165, 2361, 5022],
 [9628,
  20000,
  5535,
  18802,
  43635,
  39797,
  13497,
  47019,
  40264,
  24125,
  35691,
  18802,
  45339,
  4534,
  38414,
  46119,
  36747,
  33784,
  19944,
  6708,
  24177,
  30072,
  9873,
  25589,
  38036,
  33131,
  8646

In [124]:
sen_length = 50
embadding_doc_test = pad_sequences(onehot_rep_test,padding='pre', maxlen=sen_length)
print(embadding_doc_test)

[[    0     0 43635 ... 25589 38036 36964]
 [    0     0     0 ... 38036 17498 39607]
 [    0     0     0 ... 26165  2361  5022]
 ...
 [    0     0     0 ...  4120  5705 33050]
 [    0     0     0 ... 25589 38036 11924]
 [    0     0     0 ... 40839 20528 24956]]


In [125]:
x_test_final = np.array(embadding_doc_test)

In [126]:
y_pred_test = mdl_xgb.predict(x_test_final)

In [130]:
pd.DataFrame({ 'Predicted': y_pred_test}).head(10)

Predicted
0          2
1          4
2          1
3          2
4          2
5          7
6          4
7          9
8          2
9          9